### ISSUE TITLE
New avatar for member in registration form

### ISSUE THREAD

**Issue by florianniebuhr** [katgirl/contao-avatar#47]
Hallo Kirsten,

ich habe deine Erweiterung in Verwendung mit Contao 3.5 und habe Probleme beim Speichern des avatars im Registrieren Form Modul im FE.

Contao 3.5 mit Composer
contao-avatar 3.2.5 (von heute) ;-)

AvatarWidget.php, 302
   $objMember->save(); 

nicht aufrufbar und bricht dann ab.

Fehlermeldung:

Warning: Creating default object from empty value in system/modules/avatar/library/Avatar/AvatarWidget.php on line 301
#0 system/modules/avatar/library/Avatar/AvatarWidget.php(301): __error(2, 'Creating defaul...', '/Users/floriann...', 301, Array)
#1 system/modules/core/modules/ModuleRegistration.php(201): KirstenRoschanski\Avatar\Widget\AvatarWidget->validate()
#2 system/modules/xtmembers/modules/ModuleRegistrationExtended.php(46): Contao\ModuleRegistration->compile()
#3 system/modules/core/modules/Module.php(282): Contao\ModuleRegistrationExtended->compile()
#4 system/modules/core/modules/ModuleRegistration.php(58): Contao\Module->generate()
#5 system/modules/core/elements/ContentModule.php(59): Contao\ModuleRegistration->generate()
#6 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#7 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#8 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#11 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#12 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#13 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 index.php(20): Contao\FrontendIndex->run()
#15 {main}

Fatal error: Call to undefined method stdClass::save() in /Users/florianniebuhr/Sites/bureau5/sac/system/modules/avatar/library/Avatar/AvatarWidget.php on line 302

Was kann das sein?

Besten Gruß

**Comment by WuRmL** [comment]
Gibt es mittlerweile eine Lösung für das Problem?

Benutze Avatar 3.2.3 unter Contao 3.5.6 

Habe den Post von "fivebytes" gefunden und gehofft, dass seine Lösung den Fehler behebt.
https://community.contao.org/de/show...hlen-(gel%F6st!)

Ich habe die Zeile
- protected $blnSubmitInput = true;
durch die Zeile
+ protected $blnSubmitInput = false;
ersetzt.

Allerdings konnte das den Fehler bei mir nicht beheben.

Eine normale Registrierung ohne Avatar funktioniert problemlos, aber sobald ein Bild ausgewählt ist, kommt die über mir gepostete Fehlermeldung.
Ich habe auch gelesen, dass man die Zeile 302 löschen kann, dann ist zwar der untere Fatal Error weg, aber funktionieren tut es immer noch nicht.

Vielleicht hat ja mittlerweile jemand eine Lösung

**Comment by katgirl** [comment]
Könnt ihr das Senario mal beschreiben, denn ich kann dieses nicht reproduzieren bei mir.

**Comment by WuRmL** [comment]
Meine installierten Erweiterungen sind:
- avatar (3.2.3)
- dk_mmenu (1.5.1)
- memberlist (1.3.2)
- MultiColumnWizard (3.3.3)
- rocksolid-columns (1.0.6)
- rocksolid-slider (1.5.7)
- xtmembers_fieldeditor (3.2.0)

Ich habe in meinem Registrierungsformular 4 eigene Felder über den Fieldeditor erstellt.
Die funktionieren soweit auch.
Ich kann den Mitgliedern im Backend ein Avatar problemlos zuweisen.
Das einzige Problem ist bei der Frontendregistrierung, wenn ich ein Avatar ausgewählt habe.

**Comment by katgirl** [comment]
bedeutet, das du in der Registrierung das machst? Das habe ich in der Tat nie getestet, weil ich das immer erst mache wenn das Mitglied schon angelegt ist. Damit ich die ID dann mit an den Avatar hängen kann. schaue ich mir mal an. 

Als Workflow nimm den Avatar aus der Registrierung raus und lasse ihn nur bei den Mitgliedern ausgeben, da läuft er.

**Comment by WuRmL** [comment]
Ja genau, ich habe den Avatar-Upload in der Registrierung. 
Wie meinst du das, dass ich den Avatar aus der Registrierung nehmen soll?
Dann habe ich ja nicht mehr die Möglichkeit einen Avatar auszuwählen.
Das Mitglied soll sich im Nachhinein nicht mehr anmelden und seine Daten ändern.
Also muss es über die Registrierung funktionieren.

**Comment by WuRmL** [comment]
Konntest du herausfinden woran das liegt?
