### ISSUE TITLE
Warning: hex2bin() expects parameter 1 to be string

### ISSUE THREAD

**Issue by akroii** [katgirl/contao-avatar#49]
```
Warning: hex2bin() expects parameter 1 to be string, array given in C:\xampp\htdocs\tps\system\modules\core\library\Contao\StringUtil.php on line 547
#0 [internal function]: __error(2, 'hex2bin() expec...', 'C:\\xampp\\htdocs...', 547, Array)
#1 C:\xampp\htdocs\tps\system\modules\core\library\Contao\StringUtil.php(547): hex2bin(Array)
#2 C:\xampp\htdocs\tps\system\modules\avatar\library\Avatar\AvatarBackend.php(45): Contao\StringUtil::uuidToBin(Array)
#3 C:\xampp\htdocs\tps\system\modules\core\controllers\BackendFile.php(119): KirstenRoschanski\Avatar\AvatarBackend->loadFile(Array, Object(Contao\DC_File))
#4 C:\xampp\htdocs\tps\contao\file.php(20): Contao\BackendFile->run()
#5 {main}
```

Fehler tritt in Contao 3.5.9 auf, wenn man im Backend die Einstellungen beim Avatar Standardbild vornehmen will.

**Comment by BugBuster1701** [comment]
Die PHP Version ist zu klein. Sollte mindestens PHP 5.4 sein.

**Comment by akroii** [comment]
PHP Version ist 5.6.14

**Comment by katgirl** [comment]
Was steht denn bei dir in der localconfig in den Variablen:
```php
$GLOBALS['TL_DCA']['tl_settings']['fields']['avatar_fallback_image']

$GLOBALS['TL_DCA']['tl_settings']['fields']['avatar_dir']
```

Wie ich das sehe hast du in Einstellungen nicht die Pflichtfelder ausgefüllt ;-)

**Comment by akroii** [comment]
```
$GLOBALS['TL_CONFIG']['avatar_dir'] = '63585d5a-23da-11e5-8a42-0862664830f2';
$GLOBALS['TL_CONFIG']['avatar_maxsize'] = 2097152;
$GLOBALS['TL_CONFIG']['avatar_filetype'] = 'png,jpg';
$GLOBALS['TL_CONFIG']['avatar_maxdims'] = 'a:3:{i:0;s:3:"300";i:1;s:0:"";i:2;s:12:"proportional";}';
$GLOBALS['TL_CONFIG']['avatar_rename'] = false;
```

**Comment by akroii** [comment]
`avatar_fallback_image` habe ich nicht angelegt

**Comment by akroii** [comment]
UPDATE:
`$GLOBALS['TL_CONFIG']['avatar_fallback_image'] = '5bf09e05-3ffc-11e5-932b-0862664830f2';`

Fehler tritt trotzdem auf
